CREATE TABLE IF NOT EXISTS letter_submissions (
  letter_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_token VARCHAR(64) NOT NULL,
  share_url VARCHAR(1024) NOT NULL,
  recipient_name VARCHAR(32) NOT NULL,
  sender_name VARCHAR(32) NOT NULL,
  letter_content TEXT NOT NULL,
  content_type VARCHAR(16) NOT NULL DEFAULT 'custom',
  font_type VARCHAR(16) NOT NULL DEFAULT 'mi',
  typing_speed VARCHAR(16) NOT NULL DEFAULT 'normal',
  media_type VARCHAR(16) NOT NULL DEFAULT 'none',
  media_url VARCHAR(1024) DEFAULT NULL,
  media_name VARCHAR(255) DEFAULT NULL,
  media_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  music_source VARCHAR(16) NOT NULL DEFAULT 'none',
  music_url VARCHAR(1024) DEFAULT NULL,
  music_data JSON DEFAULT NULL,
  playback_mode VARCHAR(16) NOT NULL DEFAULT 'full',
  snippet_start_time INT UNSIGNED NOT NULL DEFAULT 0,
  client_ip VARCHAR(64) DEFAULT NULL,
  account_id VARCHAR(50) DEFAULT NULL,
  retention_days INT UNSIGNED NOT NULL DEFAULT 30,
  expires_at DATETIME DEFAULT NULL,
  access_limit INT UNSIGNED NOT NULL DEFAULT 1,
  access_used INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (letter_id),
  UNIQUE KEY uq_letter_share_token (share_token),
  KEY idx_created_at (created_at),
  KEY idx_expires_at (expires_at),
  KEY idx_account_id (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
